volumes:
  green-data:
    external: false
services:

  fastapi:
    build:
      context: green_creme
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://example_user:secret@db/db
      WAIT_HOSTS: db:5432
      PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./green_creme:/app

  db:
    image: postgres:15.2-bullseye
    volumes:
      - green-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: example_user
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: db
    ports:
      - 15432:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_GREEN_CREME_API_HOST: http://localhost:8000
